<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oliverius, Miranda">

<title>Chocolate Chip Cookie Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="cookie_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="cookie_analysis_files/libs/quarto-html/quarto.js"></script>
<script src="cookie_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="cookie_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="cookie_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="cookie_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cookie_analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="cookie_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="cookie_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="cookie_analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chocolate Chip Cookie Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Oliverius, Miranda </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>Baking is a game of chemistry, in which various ingredients engage in a number of chemical reactions to result in tasty desserts. But not all baking attempts end well. For example, if you use eggs straight from the fridge instead of allowing them to reach room temperature, cookie dough won’t aerate properly and the cookies might not be as fluffy as you desire.</p>
<p>When approaching the chemistry of a cookie, three of the main components are flour, fat, and sugar. Flour is a binding agent that provides structure and density. Fat adds flavor and influences the texture of a cookie; more fat increases chewiness, less fat increases crunchiness. Lastly, sugar provides taste and influences the tenderness and spread of a cookie.</p>
<p>A basic cookie ratio is 3:2:1- three parts flour, two parts fat, and one part sugar. As previously noted, flour predominantly serves as a binding agent, while fat and sugar can be manipulated to influence the taste and texture of a cookie.</p>
</section>
<section id="data-source" class="level2">
<h2 class="anchored" data-anchor-id="data-source">Data Source</h2>
<p>The dataset is composed of information about chocolate chip cookie recipes. The data was provided by Elle O’Brien in a GitHub repository. O’Brien details that the data was scraped from recipe databases AllRecipes and Epicurious, along with various other internet websites. The repository included a text file of the recipe instructions as well as a dataset containing information about the recipes’ ingredients and recipe ratings.</p>
<section id="list-of-features" class="level4">
<h4 class="anchored" data-anchor-id="list-of-features">List of Features</h4>
<ol type="1">
<li>Ingredient: The name of the ingredient</li>
<li>Text: The whole text description of the ingredient and the quantity (after scaling to 48 servings)</li>
<li>Recipe_Index: A tag used to label recipe sources</li>
<li>Rating: If a rating was available on the recipe, it is provided as a numeric value normalized to be between 0 and 1</li>
<li>Quantity: The scalar quantity of the ingredient, after scaling to 48 servings</li>
<li>Unit: The unit that the ingredient is measured in</li>
</ol>
</section>
</section>
<section id="problem-framing" class="level2">
<h2 class="anchored" data-anchor-id="problem-framing">Problem Framing</h2>
<p>This analysis will explore the ratio of flour, fat, and sugar in chocolate chip cookie recipes: Does changing the amount of fat or sugar impact the rating of a chocolate chip cookie recipe?</p>
</section>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">Data Preparation</h2>
<section id="preliminaries" class="level3">
<h3 class="anchored" data-anchor-id="preliminaries">Preliminaries</h3>
<p>First, the necessary libraries are imported, the dataset is loaded, and all column names are changed to snake case:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse, <span class="at">quietly=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor, <span class="at">quietly=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>cookie_recipes_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"choc_chip_cookie_ingredients.csv"</span>, <span class="at">show_col_types=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...1`</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a copy of data for analysis</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cookie_analysis <span class="ot">&lt;-</span> cookie_recipes_raw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># clean non-syntactic column names (snake-case is personal preference)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>cookie_analysis <span class="ot">&lt;-</span> janitor<span class="sc">::</span><span class="fu">clean_names</span>(cookie_analysis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Initial data exploration is completed to evaluate any necessary cleaning and the relevant variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view dataset head</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cookie_analysis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
     x1 ingredient        text                recipe_index rating quantity unit 
  &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;               &lt;chr&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;
1     1 all purpose flour 3.0 cups all purpo… AR_1          0.921     3    cup  
2     2 all purpose flour 2.8000000000000003… AR_10         0.905     2.8  cup  
3     3 all purpose flour 1.1076923076923078… AR_101        0.6       1.11 cup  
4     4 all purpose flour 3.333333333333333 … AR_102        0.938     3.33 cup  
5     5 all purpose flour 2.0 cups all purpo… AR_103        0.881     2    cup  
6     6 all purpose flour 9.0 cups unbleache… AR_107        0.927     9    cup  </code></pre>
</div>
</div>
<p>The head of the dataset reveals that the Text variable is redundant; the information in this column is broken out into a more usable format in the Ingredient, Quantity, and Unit variables.</p>
<p>This means that the only columns necessary for our analysis are recipe_index, quantity, unit, ingredient, and rating.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select columns for analysis</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>cookie_analysis <span class="ot">&lt;-</span> cookie_analysis <span class="sc">|&gt;</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(recipe_index, quantity, unit, ingredient, rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To prepare the dataset for flour-fat-sugar ratio analysis, ingredients are viewed and categorized:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view unique ingredients</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>cookie_analysis <span class="sc">|&gt;</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(ingredient)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 68 × 1
   ingredient       
   &lt;chr&gt;            
 1 all purpose flour
 2 almond extract   
 3 almonds          
 4 applesauce       
 5 baking powder    
 6 baking soda      
 7 bourbon          
 8 bread flour      
 9 brown rice flour 
10 butter           
# ℹ 58 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># update data for flour-fat-sugar ratio analysis</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>ratio_analysis_incl_outliers <span class="ot">&lt;-</span> cookie_analysis <span class="sc">|&gt;</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># classify ingredients as flour, fat, or sugar</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">category =</span> <span class="fu">case_when</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>      <span class="co"># anything that includes the string "flour" categorized as flour</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(ingredient, <span class="st">"flour"</span>) <span class="sc">~</span> <span class="st">"flour"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>      <span class="co"># "wheat" categorized as flour</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>      ingredient <span class="sc">==</span> <span class="st">"wheat"</span> <span class="sc">~</span> <span class="st">"flour"</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>      <span class="co"># can't use str_detect for "butter" bc "peanut butter" and "peanut butter chips" are included in data</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>      <span class="co"># anything that matches "butter", "shortening", "margarine", or "vegetable oil" categorized as fat</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>      ingredient <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"butter"</span>, <span class="st">"shortening"</span>, <span class="st">"margarine"</span>, <span class="st">"vegetable oil"</span>) <span class="sc">~</span> <span class="st">"fat"</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>      <span class="co"># anything that includes the string "sugar" categorized as sugar</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(ingredient, <span class="st">"sugar"</span>) <span class="sc">~</span> <span class="st">"sugar"</span>,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>      <span class="co"># anything that matches "corn syrup", "honey", "maple", or "molasses" categorized as sugar</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>      ingredient <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"corn syrup"</span>, <span class="st">"honey"</span>, <span class="st">"maple"</span>, <span class="st">"molasses"</span>) <span class="sc">~</span> <span class="st">"sugar"</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"unknown"</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, ingredients categorized as flour, fat, or sugar are reviewed to ensure the categories make sense:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view ingredients that were categorized</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>ratio_analysis_incl_outliers <span class="sc">|&gt;</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(category <span class="sc">!=</span> <span class="st">"unknown"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(ingredient, category) <span class="sc">|&gt;</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 2
   ingredient        category
   &lt;chr&gt;             &lt;chr&gt;   
 1 butter            fat     
 2 margarine         fat     
 3 shortening        fat     
 4 vegetable oil     fat     
 5 all purpose flour flour   
 6 bread flour       flour   
 7 brown rice flour  flour   
 8 cake flour        flour   
 9 flour             flour   
10 wheat             flour   
11 wheat flour       flour   
12 corn syrup        sugar   
13 honey             sugar   
14 maple             sugar   
15 molasses          sugar   
16 sugar             sugar   
17 light brown sugar sugar   
18 dark brown sugar  sugar   </code></pre>
</div>
</div>
<p>Then, ingredient categorized as “unknown” are reviewed to evaluate whether any additional values should be categorized as flour, fat, or sugar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view ingredients that were categorized as "unknown"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ratio_analysis_incl_outliers <span class="sc">|&gt;</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(category <span class="sc">==</span> <span class="st">"unknown"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(ingredient)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 1
   ingredient     
   &lt;chr&gt;          
 1 almond extract 
 2 almonds        
 3 applesauce     
 4 baking powder  
 5 baking soda    
 6 bourbon        
 7 cake mix       
 8 cinnamon       
 9 coconut        
10 coconut extract
# ℹ 40 more rows</code></pre>
</div>
</div>
<p>Upon review of the flour, fat, sugar, and unknown categories, the data is categorized properly and the dataset can be filtered to only include flour, fat, and sugar observations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter to relevant observations</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>ratio_analysis_incl_outliers <span class="ot">&lt;-</span> ratio_analysis_incl_outliers <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># only include categorized ingredients</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    category <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"flour"</span>, <span class="st">"fat"</span>, <span class="st">"sugar"</span>),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># only include recipes with an associated rating</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(rating)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To prepare data for ratio analysis, the units of measurement should be the same. Any non-cup units of measurement are converted to cups:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view unique units of measurement across all types of ingredients</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>ratio_analysis_incl_outliers <span class="sc">|&gt;</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(unit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 1
  unit      
  &lt;chr&gt;     
1 cup       
2 tablespoon</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to single unit of measurement</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>ratio_analysis_incl_outliers <span class="ot">&lt;-</span> ratio_analysis_incl_outliers <span class="sc">|&gt;</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 16 tablespoons = 1 cup</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">cups =</span> <span class="fu">ifelse</span>(unit <span class="sc">==</span> <span class="st">"tablespoon"</span>, quantity <span class="sc">/</span> <span class="dv">16</span>, quantity)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Some recipes include multiple types of flour, fat, and/or sugar, so the total volume (in cups) of each category is summarized:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summarize cups by category</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>cups_by_category <span class="ot">&lt;-</span> ratio_analysis_incl_outliers <span class="sc">|&gt;</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># filter to columns used in analysis</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(recipe_index, cups, category, rating) <span class="sc">|&gt;</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># group by recipe index and category</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(recipe_index, category) <span class="sc">|&gt;</span> </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># summarize sum of cups based on category</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">cups =</span> <span class="fu">sum</span>(cups),</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop_last"</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To view the information grouped by recipe, the data is pivoted into a wider format with recipes as the observations and each category (flour, fat, and sugar) as the columns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pivot tibble</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>cups_by_category <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(cups_by_category, <span class="at">names_from=</span>category, <span class="at">names_prefix=</span><span class="st">"cups_"</span>, <span class="at">values_from=</span>cups)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Rows with any NA values were spot-checked and predominantly include recipes that are substituting one or more of the key recipe components for boxed cake or cookie mixes. This code has been omitted for clarity and conciseness.</p>
<p>Recipes using boxed mixes are not representative of the data I am interested in, so rows with NA values are omitted:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># update tibble for flour-fat-sugar ratio</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>cups_by_category <span class="ot">&lt;-</span> cups_by_category <span class="sc">|&gt;</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># columns in flour-fat-sugar order</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(recipe_index, cups_flour, cups_fat, cups_sugar) <span class="sc">|&gt;</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove NA's</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This analysis is interested in changes to the fat and sugar components in cookies, so the cups are converted to “parts” where flour is equal to three parts for all recipes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># standardize cups_by_category to be parts_per_category based on 3 parts flour as the standard</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>parts_by_category <span class="ot">&lt;-</span> cups_by_category <span class="sc">|&gt;</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># create column for flour parts equal to 3.000</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">parts_flour =</span> <span class="fu">round</span>(<span class="dv">3</span>, <span class="dv">2</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># compute the divisor necessary to convert cups_fat and cups_sugar to parts</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">standard_divisor =</span> cups_flour <span class="sc">/</span> <span class="dv">3</span>,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># convert cups_fat to parts_fat</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">parts_fat =</span> <span class="fu">round</span>((cups_fat <span class="sc">/</span> standard_divisor), <span class="dv">2</span>),</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># convert cups_sugar to parts_sugar</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">parts_sugar =</span> <span class="fu">round</span>((cups_sugar <span class="sc">/</span> standard_divisor), <span class="dv">2</span>),</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(recipe_index, parts_flour, parts_fat, parts_sugar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This analysis is interested in whether recipe rating changes based on the ratio of fat and/or sugar, so the ratings by recipe are summarized before merging them with the parts by category data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create tibble summarizing rating by recipe</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>rating_by_recipe <span class="ot">&lt;-</span> cookie_analysis <span class="sc">|&gt;</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(recipe_index) <span class="sc">|&gt;</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(recipe_index, rating) <span class="sc">|&gt;</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(recipe_index, rating) <span class="sc">|&gt;</span> </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">rating =</span> <span class="fu">round</span>(rating, <span class="dv">2</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># merge parts by category with ratings</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>ratio_analysis_incl_outliers <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(parts_by_category, rating_by_recipe, <span class="at">by=</span><span class="st">"recipe_index"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># view tibble</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>ratio_analysis_incl_outliers</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 92 × 5
# Groups:   recipe_index [92]
   recipe_index parts_flour parts_fat parts_sugar rating
   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;
 1 AR_1                   3      1           2      0.92
 2 AR_10                  3      1.14        1.71   0.91
 3 AR_101                 3      2           4.12   0.6 
 4 AR_102                 3      1.2         1.2    0.94
 5 AR_103                 3      1.2         1.2    0.88
 6 AR_107                 3      0.67        2      0.93
 7 AR_108                 3      2           3      0.87
 8 AR_109                 3      1.5         1.5    0.87
 9 AR_11                  3      1.2         1.8    0.9 
10 AR_110                 3      1.5         1.5    0.87
# ℹ 82 more rows</code></pre>
</div>
</div>
</section>
<section id="outlier-removal" class="level3">
<h3 class="anchored" data-anchor-id="outlier-removal">Outlier Removal</h3>
<p>For the purposes of this analysis, values are classified as outliers and removed if they are more than roughly three standard deviations away from from the mean.</p>
<p>Using a method of outlier removal that is less conservative than the 1.5(IQR) rule will allow us to better analyze whether relatively low or high amounts of fat or sugar in a recipe have a relationship with low or high ratings.</p>
<p>Flour is omitted from outlier considerations, given that all observations have a value of three parts.</p>
<section id="lower-upper-limits-calculation" class="level4">
<h4 class="anchored" data-anchor-id="lower-upper-limits-calculation">Lower &amp; Upper Limits Calculation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute lower and upper limits for parts_fat</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>parts_fat_low <span class="ot">&lt;-</span> <span class="fu">quantile</span>(ratio_analysis_incl_outliers<span class="sc">$</span>parts_fat, <span class="fl">0.0015</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>parts_fat_high <span class="ot">&lt;-</span> <span class="fu">quantile</span>(ratio_analysis_incl_outliers<span class="sc">$</span>parts_fat, <span class="fl">0.9985</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute lower and upper limits for parts_sugar</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>parts_sugar_low <span class="ot">&lt;-</span> <span class="fu">quantile</span>(ratio_analysis_incl_outliers<span class="sc">$</span>parts_sugar, <span class="fl">0.0015</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>parts_sugar_high <span class="ot">&lt;-</span> <span class="fu">quantile</span>(ratio_analysis_incl_outliers<span class="sc">$</span>parts_sugar, <span class="fl">0.9985</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute lower and upper limits for rating</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>rating_low <span class="ot">&lt;-</span> <span class="fu">quantile</span>(ratio_analysis_incl_outliers<span class="sc">$</span>rating, <span class="fl">0.0015</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>rating_high <span class="ot">&lt;-</span> <span class="fu">quantile</span>(ratio_analysis_incl_outliers<span class="sc">$</span>rating, <span class="fl">0.9985</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-update" class="level4">
<h4 class="anchored" data-anchor-id="data-update">Data Update</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove outliers</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>ratio_analysis <span class="ot">&lt;-</span> ratio_analysis_incl_outliers <span class="sc">|&gt;</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    parts_fat <span class="sc">&gt;=</span> parts_fat_low <span class="sc">&amp;</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    parts_fat <span class="sc">&lt;=</span> parts_fat_high <span class="sc">&amp;</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    parts_sugar <span class="sc">&gt;=</span> parts_sugar_low <span class="sc">&amp;</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    parts_sugar <span class="sc">&lt;=</span> parts_sugar_high <span class="sc">&amp;</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    rating <span class="sc">&gt;=</span> rating_low <span class="sc">&amp;</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>    rating <span class="sc">&lt;=</span> rating_high</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis">Data Analysis</h2>
<p>The variables are analyzed using visualizations and descriptive statistics to identify any trends or relationships between the parts fat, parts sugar, and ratings. Flour is omitted from the below analyses as it is held constant at a value of three parts.</p>
<section id="visual-analysis" class="level3">
<h3 class="anchored" data-anchor-id="visual-analysis">Visual Analysis</h3>
<p>First, histograms are plotted to identify any trends in the distribution of each variable’s values. Then, scatter plots are created to view the relationship between fat and sugar ratios and the recipe rating:</p>
<section id="plot-1a.-histogram-parts-fat-given-three-parts-flour" class="level4">
<h4 class="anchored" data-anchor-id="plot-1a.-histogram-parts-fat-given-three-parts-flour">Plot 1A. Histogram: Parts Fat, Given Three Parts Flour</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view boxplot of parts_fat</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>plot_1a <span class="ot">&lt;-</span> ratio_analysis <span class="sc">|&gt;</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>parts_fat)) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">binwidth=</span><span class="fl">1.0</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">c</span>(<span class="fl">0.0</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">3.0</span>, <span class="fl">4.0</span>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"1A. Histogram: Parts Fat, Given Three Parts Flour"</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"# Parts"</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>plot_1a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cookie_analysis_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot 1A demonstrates that given 3.00 parts flour, most recipes use 1.00 to 2.00 parts fat. Recipes with 0.00 to 1.00 parts fat make up the second largest bin on the plot, indicating that the data is asymmetrical and right-skewed.</p>
</section>
<section id="plot-1b.-histogram-parts-sugar-given-three-parts-flour" class="level4">
<h4 class="anchored" data-anchor-id="plot-1b.-histogram-parts-sugar-given-three-parts-flour">Plot 1B. Histogram: Parts Sugar, Given Three Parts Flour</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view boxplot of parts_sugar</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>plot_1b <span class="ot">&lt;-</span> ratio_analysis <span class="sc">|&gt;</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>parts_sugar)) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">binwidth=</span><span class="fl">0.5</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">c</span>(<span class="fl">0.0</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">1.5</span>, <span class="fl">2.0</span>, <span class="fl">2.5</span>, <span class="fl">3.0</span>, <span class="fl">3.5</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"1B. Histogram: Parts Sugar, Given Three Parts Flour"</span>,</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"# Parts"</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>plot_1b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cookie_analysis_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot 1B demonstrates that given 3.00 parts flour, most recipes use between 1.50 and 2.00 parts sugar. The data indicates a relatively symmetrical distribution.</p>
</section>
<section id="plot-1c.-histogram-recipe-rating" class="level4">
<h4 class="anchored" data-anchor-id="plot-1c.-histogram-recipe-rating">Plot 1C. Histogram: Recipe Rating</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view boxplot of parts_sugar</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>plot_1c <span class="ot">&lt;-</span> ratio_analysis <span class="sc">|&gt;</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>rating)) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">binwidth=</span><span class="fl">0.25</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks=</span><span class="fu">c</span>(<span class="fl">0.0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="fl">1.0</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"1C. Histogram: Recipe Rating"</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"Rating"</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>plot_1c</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cookie_analysis_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot 1C demonstrates that rating is a left-skewed distribution with most ratings between 0.75 and 1.00.</p>
</section>
<section id="plot-1d.-scatterplot-rating-vs.-parts-fat" class="level4">
<h4 class="anchored" data-anchor-id="plot-1d.-scatterplot-rating-vs.-parts-fat">Plot 1D. Scatterplot: Rating vs.&nbsp;Parts Fat</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>plot_1d <span class="ot">&lt;-</span> ratio_analysis <span class="sc">|&gt;</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span>parts_fat,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span>rating</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"1D. Scatterplot: Rating vs. Parts Fat"</span>,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"Fat (parts)"</span>,</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span><span class="st">"Rating"</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>plot_1d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cookie_analysis_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot 1D demonstrates no visually discernible patterns based on the plotted points. A large range of ratings can be viewed for similar amounts of fat, indicating that there is not a relationship between rating and parts fat.</p>
</section>
<section id="plot-1e.-scatterplot-rating-vs.-parts-sugar" class="level4">
<h4 class="anchored" data-anchor-id="plot-1e.-scatterplot-rating-vs.-parts-sugar">Plot 1E. Scatterplot: Rating vs.&nbsp;Parts Sugar</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>plot_1e <span class="ot">&lt;-</span> ratio_analysis <span class="sc">|&gt;</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span>parts_sugar,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span>rating</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"1E. Scatterplot: Rating vs. Parts Sugar"</span>,</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"Sugar (parts)"</span>,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span><span class="st">"Rating"</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>plot_1e</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cookie_analysis_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot 1E demonstrates no visually discernible patterns based on the plotted points. A large range of ratings can be viewed for similar amounts of sugar, indicating that there is not a relationship between rating and parts sugar.</p>
</section>
<section id="plot-1f.-scatterplot-parts-fat-vs.-parts-sugar" class="level4">
<h4 class="anchored" data-anchor-id="plot-1f.-scatterplot-parts-fat-vs.-parts-sugar">Plot 1F. Scatterplot: Parts Fat vs.&nbsp;Parts Sugar</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>plot_1f <span class="ot">&lt;-</span> ratio_analysis <span class="sc">|&gt;</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span>parts_sugar,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span>parts_fat,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">color=</span>rating</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"1F. Scatterplot: Parts Fat vs. Parts Sugar"</span>,</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"Sugar (parts)"</span>,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span><span class="st">"Fat (parts)"</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low=</span><span class="st">"red"</span>, <span class="at">high=</span><span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title=</span><span class="fu">element_text</span>(<span class="at">hjust=</span><span class="fl">0.5</span>))</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>plot_1f</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cookie_analysis_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot 1F plots sugar and fat, with the points colored based on rating. The color legend shows a gradient where low ratings are red, mid ratings are purple, and high ratings are blue.</p>
<p>One notable observation is that none of the recipes in the dataset represent the 3:2:1 ratio of flour, fat, and sugar that is known as the basic cookie ratio, so all recipes in the dataset represent a deviation in the amount of fat and sugar.</p>
<p>Based on this plot, there are no discernible visual trends or patterns in the rating based on the combined fat and sugar information and there are a large range of ratings for similar fat and sugar ratios. This indicates that there is not a relationship between the ratio of flour, fat, and sugar to the rating of a cookie recipe.</p>
</section>
</section>
<section id="statistical-analysis" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis">Statistical Analysis</h3>
<p>First, basic descriptive statistics are generated for all numeric variables. Second, the correlation between these variables is computed.</p>
<section id="basic-descriptive-statistics" class="level4">
<h4 class="anchored" data-anchor-id="basic-descriptive-statistics">Basic Descriptive Statistics</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ratio_analysis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> recipe_index        parts_flour   parts_fat      parts_sugar   
 Length:87          Min.   :3    Min.   :0.600   Min.   :1.000  
 Class :character   1st Qu.:3    1st Qu.:1.125   1st Qu.:1.800  
 Mode  :character   Median :3    Median :1.330   Median :2.000  
                    Mean   :3    Mean   :1.324   Mean   :2.091  
                    3rd Qu.:3    3rd Qu.:1.500   3rd Qu.:2.400  
                    Max.   :3    Max.   :4.000   Max.   :3.430  
     rating     
 Min.   :0.390  
 1st Qu.:0.765  
 Median :0.870  
 Mean   :0.831  
 3rd Qu.:0.910  
 Max.   :1.000  </code></pre>
</div>
</div>
<section id="stats-parts-fat" class="level5">
<h5 class="anchored" data-anchor-id="stats-parts-fat">Stats: Parts Fat</h5>
<p>The minimum and 75th percentile demonstrate that the bottom 75% of the data has between 0.600 and 1.500 parts fat. The interquartile range shows that the middle 50% of the data is between 1.125 and 1.500 parts fat.</p>
<p>Inside of that range, the median and mean are very close (1.333 and 1.325, respectively), indicating that the effect of larger values such as the maximum of 4.000 have a limited impact on the mean, despite the asymmetry and skewness shown in Plot 1A.</p>
</section>
<section id="stats-parts-sugar" class="level5">
<h5 class="anchored" data-anchor-id="stats-parts-sugar">Stats: Parts Sugar</h5>
<p>The minimum and 75th percentile demonstrate that the bottom 75% of the data has between 1.000 and 2.400 parts sugar. The interquartile range shows that the middle 50% of the data is between 1.800 and 2.400 parts sugar.</p>
<p>Inside of that range, the median and mean are very close (2.000 and 2.091, respectively). In addition, the minimum and maximum are 1.000 and 1.429 parts sugar away from the median, respectively. This supports the relatively symmetrical distribution shown in Plot 1B.</p>
</section>
<section id="stats-rating" class="level5">
<h5 class="anchored" data-anchor-id="stats-rating">Stats: Rating</h5>
<p>The minimum and 75th percentile demonstrate that the bottom 75% of the recipes have a rating between 0.3857 and 0.9100. The interquartile range shows that the middle 50% of the recipes were rated 0.7673 to 0.9100.</p>
<p>Inside of that range, the median and mean are 0.8737 and 0.8307, respectively. Considering that the ratings are on a scale from zero to one, this difference indicates that lower values such as the minimum of 0.3857 did influence the mean. This supports the skewness noted in Plot 1C.</p>
</section>
</section>
<section id="correlation-matrix" class="level4">
<h4 class="anchored" data-anchor-id="correlation-matrix">Correlation Matrix</h4>
<p>A simple correlation matrix is viewed to assess the degree to which there is a linear relationship between the variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prepare data for correlation matrix</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>ratio_analysis_numeric <span class="ot">&lt;-</span> ratio_analysis <span class="sc">|&gt;</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># set recipe_index as index in R </span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="at">var=</span><span class="st">"recipe_index"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># select columns for correlation matrix</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(parts_fat, parts_sugar, rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate correlation matrix</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(ratio_analysis_numeric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             parts_fat parts_sugar     rating
parts_fat    1.0000000   0.3198080 -0.2132385
parts_sugar  0.3198080   1.0000000 -0.2422759
rating      -0.2132385  -0.2422759  1.0000000</code></pre>
</div>
</div>
<p>Based on the matrix above, none of the variables have a strong correlation with the other variables. The correlation between parts fat and rating is -0.21 and the correlation between parts sugar and rating is -0.24.</p>
</section>
</section>
</section>
<section id="linear-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-models">Linear Regression Models</h2>
<p>While the visualizations and statistics generated indicate that there is no relationship between the amount of fat or sugar in a recipe and the corresponding rating, linear regression models are generated and compared as a mental exercise.</p>
<p>Each model is assessed based on its t-values and adjusted R-squared values before the models are compared to each other based on adjusted R-squared and Akaike information criterion (AIC) values.</p>
<section id="fat-model" class="level3">
<h3 class="anchored" data-anchor-id="fat-model">Fat Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate model predicting rating based on parts fat</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>fat_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> parts_fat, <span class="at">data=</span>ratio_analysis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view model summary</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>summary_fat <span class="ot">&lt;-</span> <span class="fu">summary</span>(fat_model)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>summary_fat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ parts_fat, data = ratio_analysis)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.46562 -0.04102  0.04239  0.07871  0.16928 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.90119    0.03720  24.228   &lt;2e-16 ***
parts_fat   -0.05298    0.02633  -2.012   0.0474 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1209 on 85 degrees of freedom
Multiple R-squared:  0.04547,   Adjusted R-squared:  0.03424 
F-statistic: 4.049 on 1 and 85 DF,  p-value: 0.04736</code></pre>
</div>
</div>
<p>The fat model attempts to predict recipe rating based on the number of parts fat, given three parts of flour. The t-value of 0.052 indicates that the fat predictor is not significant, and the adjusted R-squared value of 0.03244 indicates that fat explains an extremely small amount of the variability observed in recipe ratings.</p>
</section>
<section id="sugar-model" class="level3">
<h3 class="anchored" data-anchor-id="sugar-model">Sugar Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate model predicting rating based on parts sugar</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>sugar_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> parts_sugar, <span class="at">data=</span>ratio_analysis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view model summary</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>summary_sugar <span class="ot">&lt;-</span> <span class="fu">summary</span>(sugar_model)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>summary_sugar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ parts_sugar, data = ratio_analysis)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.41427 -0.05623  0.04389  0.07849  0.19852 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.94784    0.05234  18.108   &lt;2e-16 ***
parts_sugar -0.05586    0.02426  -2.302   0.0238 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1201 on 85 degrees of freedom
Multiple R-squared:  0.0587,    Adjusted R-squared:  0.04762 
F-statistic:   5.3 on 1 and 85 DF,  p-value: 0.02376</code></pre>
</div>
</div>
<p>The sugar model attempts to predict recipe rating based on the number of parts sugar, given three parts of flour. The t-value of 0.023 indicates that the sugar predictor is significant, but the adjusted R-squared value of 0.04827 indicates that sugar explains an extremely small amount of the variability observed in recipe ratings.</p>
</section>
<section id="fat-sugar-model" class="level3">
<h3 class="anchored" data-anchor-id="fat-sugar-model">Fat &amp; Sugar Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate model predicting rating based on parts fat and parts sugar</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>fat_sugar_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> parts_fat <span class="sc">+</span> parts_sugar, <span class="at">data=</span>ratio_analysis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view model summary</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>summary_fat_sugar <span class="ot">&lt;-</span> <span class="fu">summary</span>(fat_sugar_model)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>summary_fat_sugar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ parts_fat + parts_sugar, data = ratio_analysis)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.43705 -0.04806  0.03911  0.07392  0.19209 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.97428    0.05554  17.541   &lt;2e-16 ***
parts_fat   -0.03757    0.02745  -1.369   0.1748    
parts_sugar -0.04471    0.02548  -1.755   0.0829 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1195 on 84 degrees of freedom
Multiple R-squared:  0.07923,   Adjusted R-squared:  0.0573 
F-statistic: 3.614 on 2 and 84 DF,  p-value: 0.03122</code></pre>
</div>
</div>
<p>The fat &amp; sugar model attempts to predict recipe rating based on the number of parts fat and parts sugar, given three parts of flour. The t-values of 0.1893 and 0.0783 indicates that the fat and sugar predictors are not considered significant, and the adjusted R-squared value of 0.05661 indicates that fat and sugar explain an extremely small amount of the variability observed in recipe ratings.</p>
</section>
<section id="model-comparison" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison">Model Comparison</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create vectors of model fit metrics for comparison</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"fat"</span>, <span class="st">"sugar"</span>, <span class="st">"fat_sugar"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>adj_rsquared <span class="ot">&lt;-</span> <span class="fu">c</span>(summary_fat<span class="sc">$</span>adj.r.squared, summary_sugar<span class="sc">$</span>adj.r.squared, summary_fat_sugar<span class="sc">$</span>adj.r.squared)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>aic <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">AIC</span>(fat_model), <span class="fu">AIC</span>(sugar_model), <span class="fu">AIC</span>(fat_sugar_model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create data frame summarizing model fit metrics for comparison</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>model_fit_comparison <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> model,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">adj_rsquared =</span> adj_rsquared,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">aic =</span> aic</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># view model fit metrics side-by-side for comparison</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>model_fit_comparison</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      model adj_rsquared       aic
1       fat   0.03424089 -116.6874
2     sugar   0.04762345 -117.9014
3 fat_sugar   0.05730403 -117.8199</code></pre>
</div>
</div>
<p>Model fit is higher when the adjusted R-squared value is higher and the AIC is lower. Based on the above comparison table, the fat &amp; sugar model has the highest adjusted R-squared value, while the fat model has the lowest AIC.</p>
<p>It should be noted that adjusted R-squared is overly simplistic and will naturally get higher as additional predictors are added. The AIC is a more nuanced measure of fit.</p>
<p>Notably, the adjusted R-squared values indicate that none of the models explain enough of the variability in recipe rating to be viable in predicting recipe rating.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Based on the visualizations, descriptive statistics, and models generated, changing the ratio of fat or sugar does not impact the overall rating of a cookie recipe.</p>
<p>The fat and sugar ratio in a recipe impacts the texture and taste of the resulting cookie and people have a wide variety of preferences when it comes to chewy vs.&nbsp;crisp cookies, as well as differing taste buds.</p>
<p>In conclusion, the ratios of fat and sugar are not good predictors of recipe rating. Baking may be a game of chemistry, but getting successful reviews is influenced by the individual preferences of the people consuming the desserts.</p>
<p>It is possible that studying cookie ratings with the subjects and recipes grouped by taste or texture preferences may reveal a greater correlation between baking ratios and recipe ratings.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>The Culinary Pro. (n.d.). <em>Cookies.</em> https://www.theculinarypro.com/cookies</p>
<p>O’Brien, Elle. (2018, May 10). <em>cookies.</em> GitHub. https://github.com/the-pudding/data/tree/master/cookies</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>